runtime: python
env: flex
entrypoint: gunicorn -b 0.0.0.0:$PORT --timeout 100 main:app

runtime_config:
  python_version: 3

skip_files:
  - ^\..*$

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1

env_variables:
  GCS_BUCKET: "snt_covid19"
  GCS_MODEL: "v2/mlp.save"
  GCS_SCALER: "v2/scaler.save"
  GCS_METRICS: "v2/metrics.json"
  GCS_FEATURES: "v2/features.csv"

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
