stages:
    features_extraction:
      cmd: python feature_extraction.py
      deps:
        - feature_extraction.py
        - raw_data/
      outs:
        - dataset/features.csv
    features_val:
        cmd: python validate_features.py dataset/features.csv
        deps:
        - validate_features.py
        - dataset/features.csv  
    seirhcd_extraction:
        cmd: python fit_experiment.py dataset/features.csv data/seirhcd.csv
        deps:
        - features_val
        - dataset/features.csv
        - fit_experiment.py
        outs:
        - data/seirhcd.csv
    mlp_training:
        cmd: python model_training.py
        deps:
        - seirhcd_extraction
        - model_training.py
        - data/seirhcd.csv
        - dataset/features.csv
        model:
        - model/mlp.save
        - model/scaler.save
        - model/features.csv
        - model/metric.json
    # training:
    #   cmd: python train.py
    #   deps:
    #     - train.py
    #     - features
    #   outs:
    #     - model.pkl
    #   plots:
    #     - logs.csv:
    #         x: epoch
    #         x_label: Epoch
    #   meta: 'For deployment'